-- npcDrops by cometopapa
CreateConVar( "npcdrops_disabled", "false", FCVAR_ARCHIVE, "Enable/Disable npcDrops." )
CreateConVar( "npcdrops_itemremove", "false", FCVAR_ARCHIVE, "Remove item or don't after a while." )
CreateConVar( "npcdrops_itemremovedly", "0", FCVAR_ARCHIVE, "Remove delay only if item removing true." )
CreateConVar( "npcdrops_notify", "true", FCVAR_ARCHIVE, "Notify player if they have dropped something?" )
CreateConVar( "npcdrops_lootsound", "true", FCVAR_ARCHIVE, "Loot sound?" )
CreateConVar( "npcdrops_labels", "true", FCVAR_ARCHIVE, "Labels/Bars for items?" )
CreateConVar( "npcdrops_itemremovelabel", "true", FCVAR_ARCHIVE, "Label for remove delay?" )
CreateConVar( "npcdrops_debug", "false", FCVAR_ARCHIVE, "Enable debug mode?" )

CreateConVar( "npcdrops_basic", "Basic", FCVAR_ARCHIVE, "Basic" )
CreateConVar( "npcdrops_common", "Common", FCVAR_ARCHIVE, "Common" )
CreateConVar( "npcdrops_uncommon", "Uncommon", FCVAR_ARCHIVE, "Uncommon" )
CreateConVar( "npcdrops_rare", "Rare", FCVAR_ARCHIVE, "Rare" )
CreateConVar( "npcdrops_epic", "Epic", FCVAR_ARCHIVE, "Epic" )
